# docker build -f scripts/Linux/Debian/Dockerfile .

FROM debian:latest

RUN apt -y update
RUN apt -y upgrade
RUN apt -y install tar g++ make findutils libncurses5 libncurses5-dev curl xz-utils zlib*

