name: Build and release for target platforms

on:
  workflow_run:
    workflows: 
      - Code formatting quality and testing 
    branches: 
      - main
    types: 
      - completed

jobs:
  linux-x86_64-build:
    name: Linux x86_64 build
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: scripts/Linux/build.sh llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      - name: Set release file
        id: set_file
        run: echo "##[set-output name=files;]$(find bin/ -name '*.tar.gz')"
      - name: Set release tag
        id: set_tag
        run: echo "##[set-output name=tag;]$(cat version)"
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: ${{ steps.set_file.outputs.files }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
