name: Build and release for target platforms

on: [workflow_dispatch]

jobs:
  linux-x86_64-build:
    name: Linux x86_64 Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [arch, debian, fedora, ubuntu]
    env:
      DISTRO: ${{ matrix.distro }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker build environment
        run: docker build -f scripts/Linux/$DISTRO/Dockerfile . -t shnootalk-build-env
      - name: Build compiler
        run: |
          docker run -v `pwd`:/home/ -w /home/ shnootalk-build-env:latest \
            sh /home/scripts/Linux/build.sh llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
      - name: Set release file
        id: set_file
        run: echo "##[set-output name=files;]$(find bin/ -name '*.tar.gz')"
      - name: Set release tag
        id: set_tag
        run: echo "##[set-output name=tag;]$(cat version)"
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: ${{ steps.set_file.outputs.files }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
  linux-x86_64-appimage:
    name: Linux x86_64 AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install AppImage Builder
        run: |
          sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool
          sudo pip3 install appimage-builder
      - name: Install LLVM
        run: sudo apt install llvm-12 llvm-12-dev
      - name: Build Compiler
        run: make build -j 2
      - name: Build AppImage
        run: appimage-builder --recipe scripts/Linux/appimage-x86_64 --skip-test
      - name: Set release file
        id: set_file
        run: echo "##[set-output name=files;]$(find . -name '*.AppImage')"
      - name: Set release tag
        id: set_tag
        run: echo "##[set-output name=tag;]$(cat version)"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.set_file.outputs.files }}
          tag_name: ${{ steps.set_tag.outputs.tag }}      
  macos-x86_64-build:
    name: MacOS x86_64 Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: scripts/MacOS-x86_64/build.sh
      - name: Set release file
        id: set_file
        run: echo "##[set-output name=files;]$(find bin/ -name '*.tar.gz')"
      - name: Set release tag
        id: set_tag
        run: echo "##[set-output name=tag;]$(cat version)"
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: ${{ steps.set_file.outputs.files }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
  raspberry-pi-32bit-build:
    name: Raspberry Pi 32-bit Build
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu
        run: sudo apt install qemu binfmt-support qemu-user qemu-user-static
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker build environment
        run: docker buildx build --platform linux/arm/v7 -f scripts/Linux/debian/Dockerfile . -t shnootalk-build-env
      - name: Build 
        run: |
          docker run -v `pwd`:/home/ -w /home/ shnootalk-build-env:latest \
            sh /home/scripts/Linux/build.sh llvmorg-12.0.1/clang+llvm-12.0.1-armv7a-linux-gnueabihf.tar.xz
      - name: Set release file
        id: set_file
        run: echo "##[set-output name=files;]$(find bin/ -name '*.tar.gz')"
      - name: Set release tag
        id: set_tag
        run: echo "##[set-output name=tag;]$(cat version)"
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: ${{ steps.set_file.outputs.files }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
