name: Build and release for target platforms

on: [pull_request]

jobs:
  windows-x86_64-build:
    name: Windows x86_64 build
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install MinGW
        run: choco install mingw --force
      - name: Build
        run: scripts/Linux/build.sh https://github.com/RainingComputers/shnootalk-llvm-windows-build/releases/download/12.0.1/LLVM-12.0.1-Windows_NT-AMD64.tar.xz
      - name: Set release file
        id: set_file
        run: echo "##[set-output name=files;]$(find bin/ -name '*.tar.gz')"
      - name: Set release tag
        id: set_tag
        run: echo "##[set-output name=tag;]$(cat version)"
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: ${{ steps.set_file.outputs.files }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
